# Generated by Django 3.1.7 on 2021-07-21 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TypeReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=12, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(blank=True, max_length=15)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('technology', models.CharField(blank=True, max_length=50)),
                ('framework', models.CharField(blank=True, max_length=50)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('live_url', models.URLField(blank=True)),
                ('payment_status', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('deadline', models.DateField(blank=True)),
                ('dedicatedTime', models.IntegerField()),
                ('notification', models.CharField(blank=True, default=None, max_length=150)),
                ('development_phase', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_access.developmentstatus')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_access.serviceuser')),
                ('status', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_access.servicestatus')),
            ],
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_idea', models.TextField()),
                ('contact_date', models.DateTimeField(verbose_name='Contact Date')),
                ('contact_email', models.EmailField(max_length=200)),
                ('contact_mobile', models.IntegerField()),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_status', models.BooleanField(default=False)),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_access.typereq')),
            ],
        ),
    ]
