# Generated by Django 3.1.6 on 2021-03-20 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_idea', models.TextField()),
                ('contact_date', models.DateTimeField(verbose_name='Contact Date')),
                ('contact_email', models.EmailField(max_length=200)),
                ('contact_mobile', models.IntegerField()),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_status', models.BooleanField(default=False)),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_access.typereq')),
            ],
        ),
    ]
