# Generated by Django 3.1.6 on 2021-03-20 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_access', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typereq',
            old_name='type',
            new_name='medium',
        ),
    ]
