# Generated by Django 3.1.7 on 2021-07-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ecorpian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('office_address', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('joinDate', models.DateTimeField(verbose_name='Joining Date')),
            ],
        ),
        migrations.CreateModel(
            name='EcorpinStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_stat', models.IntegerField()),
                ('project_stat', models.IntegerField()),
                ('service_stat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Endpoint_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('end_point', models.CharField(max_length=50)),
                ('sideNav', models.CharField(max_length=20)),
                ('main_headBox', models.CharField(max_length=500)),
                ('edge_headBox', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=50)),
                ('visitor_organization', models.CharField(max_length=100)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('feedback_msg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Spotlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotlight_info', models.CharField(max_length=600)),
                ('spotlight_text', models.CharField(max_length=600)),
                ('spotlight_date', models.DateTimeField(verbose_name='Date Published')),
            ],
        ),
    ]
