# Generated by Django 3.1.6 on 2021-03-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecorpin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='endpoint_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('end_point', models.CharField(max_length=50)),
                ('sideNav', models.CharField(max_length=20)),
                ('main_headBox', models.CharField(max_length=500)),
                ('edge_headBox', models.CharField(max_length=200)),
            ],
        ),
    ]
