# Generated by Django 3.1.6 on 2021-03-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecorpin', '0002_endpoint_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='ecorpians',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('office_address', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('joinDate', models.DateTimeField(verbose_name='Joining Date')),
            ],
        ),
    ]
