# Generated by Django 3.1.6 on 2021-03-15 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecorpin', '0003_ecorpians'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ecorpians',
            new_name='ecorpian',
        ),
    ]
