# Generated by Django 3.1.6 on 2021-03-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecorpin', '0004_auto_20210315_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=50)),
                ('visitor_organization', models.CharField(max_length=100)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('feedback_msg', models.TextField()),
                ('feedback_date', models.DateTimeField(verbose_name='Feedback Date')),
            ],
        ),
    ]
