# Generated by Django 3.1.6 on 2021-03-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecorpin', '0005_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_date',
        ),
    ]
