# Generated by Django 3.1.6 on 2021-05-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecorpin', '0006_remove_feedback_feedback_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcorpinStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_stat', models.IntegerField()),
                ('project_stat', models.IntegerField()),
                ('service_stat', models.IntegerField()),
            ],
        ),
    ]
